version: '3'

services:
  backend:
    restart: always
    build: ../fastapi
    volumes:
      - ../fastapi:/backend
    ports:
      - 8000:8000

  frontend:
    restart: always
    build: .
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8080:80
